-- Base de datos
ALTER DATABASE `FAQS_QA` CHARACTER SET utf8 COLLATE utf8_general_ci;

USE `FAQS_QA`;

-- Tablas
ALTER TABLE `FAQ_FILE` CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `FAQ_TAG` CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `FILE_TAG_RELATION` CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `USER_ACCOUNT` CHARACTER SET utf8 COLLATE utf8_general_ci;

-- Campos
ALTER TABLE `FAQ_TAG` MODIFY `TAG_NAME` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL, MODIFY `TAG` VARCHAR(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;

ALTER TABLE `FILE_TAG_RELATION` MODIFY `NAME_RELATION` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL, MODIFY `RELATION` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL;

ALTER TABLE `FAQ_FILE` MODIFY `ARTICLE_NAME` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL, MODIFY `ARTICLE_TEXT` LONGTEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;

ALTER TABLE `USER_ACCOUNT` MODIFY `USER_ID` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL, MODIFY `USER_PASSWORD` VARCHAR(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;


