-- Base de datos
ALTER DATABASE `FAQS_DEV` CHARACTER SET utf8 COLLATE utf8_general_ci;

-- Tablas
ALTER TABLE `FAQS_DEV`.`FAQ_FILE` CHARSET=utf8 COLLATE=utf8_general_ci;
ALTER TABLE `FAQS_DEV`.`FAQ_TAG` CHARSET=utf8 COLLATE=utf8_general_ci;
ALTER TABLE `FAQS_DEV`.`FILE_TAG_RELATION` CHARSET=utf8 COLLATE=utf8_general_ci;
ALTER TABLE `FAQS_DEV`.`USER_ACCOUNT` CHARSET=utf8 COLLATE=utf8_general_ci;

-- Campos
ALTER TABLE `FAQS_DEV`.`FAQ_TAG` CHANGE `TAG_NAME` `TAG_NAME` VARCHAR(50) CHARSET utf8 COLLATE utf8_general_ci NOT NULL, CHANGE `TAG` `TAG` VARCHAR(20) CHARSET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `FAQS_DEV`.`FILE_TAG_RELATION` CHANGE `NAME_RELATION` `NAME_RELATION` VARCHAR(50) CHARSET utf8 COLLATE utf8_general_ci NOT NULL, CHANGE `RELATION` `RELATION` VARCHAR(50) CHARSET utf8 COLLATE utf8_general_ci NULL;
ALTER TABLE `FAQS_DEV`.`FAQ_FILE` CHANGE `ARTICLE_NAME` `ARTICLE_NAME` VARCHAR(50) CHARSET utf8 COLLATE utf8_general_ci NOT NULL, CHANGE `ARTICLE_TEXT` `ARTICLE_TEXT` LONGTEXT CHARSET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `FAQS_DEV`.`USER_ACCOUNT` CHANGE `USER_ID` `USER_ID` VARCHAR(50) CHARSET utf8 COLLATE utf8_general_ci NOT NULL, CHANGE `USER_PASSWORD` `USER_PASSWORD` VARCHAR(20) CHARSET utf8 COLLATE utf8_general_ci NOT NULL;
