-- Renombramos las tablas
RENAME TABLE archivos TO FAQ_FILE;
RENAME TABLE accounts TO USER_ACCOUNT;
RENAME TABLE tags TO FAQ_TAG;
RENAME TABLE relates TO FILE_TAG_RELATION;

-- Renombramos las columnas de las tablas

--Tabla FAQ_FILE
ALTER TABLE FAQ_FILE CHANGE id FAQ_FILE_ID INT(10) UNSIGNED NOT NULL;
ALTER TABLE FAQ_FILE CHANGE nombre ARTICLE_NAME  VARCHAR(50) NOT NULL;
ALTER TABLE FAQ_FILE CHANGE texto ARTICLE_TEXT  LONGTEXT NOT NULL;
ALTER TABLE FAQ_FILE CHANGE visitas VISITS INT(10) NOT NULL;
ALTER TABLE FAQ_FILE CHANGE createdAt CREATED_AT DATETIME;
ALTER TABLE FAQ_FILE CHANGE updatedAt UPDATED_AT DATETIME;

-- Tabla FAQ_TAG
ALTER TABLE FAQ_TAG CHANGE id FAQ_TAG_ID INT(10) UNSIGNED NOT NULL;
ALTER TABLE FAQ_TAG CHANGE nombre TAG_NAME VARCHAR(50) NOT NULL;
ALTER TABLE FAQ_TAG CHANGE tag TAG VARCHAR(20) NOT NULL;
ALTER TABLE FAQ_TAG CHANGE createdAt CREATED_AT DATETIME;
ALTER TABLE FAQ_TAG CHANGE updatedAt UPDATED_AT DATETIME;

-- Tabla USER_ACCOUNT
ALTER TABLE USER_ACCOUNT CHANGE `user` USER_ID VARCHAR(50) NOT NULL;
ALTER TABLE USER_ACCOUNT CHANGE `password` USSER_PASSWORD VARCHAR(20) NOT NULL;

-- Tabla FILE_TAG_RELATION
ALTER TABLE FILE_TAG_RELATION CHANGE id FILE_TAG_RELATION_ID INT(10) UNSIGNED NOT NULL;
ALTER TABLE FILE_TAG_RELATION CHANGE nombre NAME_RELATION VARCHAR(50) NOT NULL;
ALTER TABLE FILE_TAG_RELATION CHANGE relate RELATION VARCHAR(50);
ALTER TABLE FILE_TAG_RELATION CHANGE createdAt CREATED_AT DATETIME;
ALTER TABLE FILE_TAG_RELATION CHANGE updatedAt UPDATED_AT DATETIME;
